import type { PhotoDetail, PhotoListItem } from "@mybestphotos/shared";

export const FALLBACK_ITEMS: PhotoListItem[] = [
  {
    id: 1,
    sourceRoot: "/photos/repo1",
    relativePath: "demo/allie-dog.jpg",
    filename: "2020_07_14_1752.jpg",
    photoTakenAt: "2020-07-14T17:52:00.000Z",
    cameraMake: "Canon",
    cameraModel: "EOS R6",
    printScore12x18: 0.92,
    printScore8x10: 0.9,
    printScore6x8: 0.94,
    curationScore: 0.93,
    descriptionText: "Young girl smiling with golden retriever in natural light.",
    keepFlag: true,
    rejectFlag: false,
    favoriteFlag: true,
  },
];

export const FALLBACK_DETAIL: PhotoDetail = {
  id: 1,
  sourceRoot: "/photos/repo1",
  relativePath: "demo/allie-dog.jpg",
  filename: "2020_07_14_1752.jpg",
  extension: "jpg",
  width: 4032,
  height: 3024,
  photoTakenAt: "2020-07-14T17:52:00.000Z",
  photoTakenAtSource: "filename",
  cameraMake: "Canon",
  cameraModel: "EOS R6",
  descriptionText: "Young girl smiling with golden retriever in natural light.",
  descriptionJson: { categories: ["people", "pets", "summer"] },
  metrics: {
    blurScore: 0.12,
    brightnessScore: 0.88,
    contrastScore: 0.85,
    entropyScore: 0.81,
    noiseScore: 0.9,
    printScore6x8: 0.94,
    printScore8x10: 0.9,
    printScore12x18: 0.92,
    technicalQualityScore: 0.92,
    semanticRelevanceScore: 0.84,
    curationScore: 0.9,
  },
  labels: {
    keepFlag: true,
    rejectFlag: false,
    favoriteFlag: true,
    printCandidate6x8: true,
    printCandidate8x10: true,
    printCandidate12x18: true,
    notes: "Stub demo mode.",
  },
};
